export const ADD_TODO = 'add_todo'
export const DELETE_TODO = 'delete_todo'
export const DELETE_FINISHED_TODO = 'delete_finished_todo'
export const IS_SELECTED_ALL_TODO = 'is_selected_all_todo'
export const CHANGE_TODO = 'change_todo'
